# Generated by Django 3.2.3 on 2021-05-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
