# Generated by Django 3.2.3 on 2021-05-27 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_guardian_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='user',
        ),
    ]
