# Generated by Django 3.2.3 on 2021-05-29 14:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_remove_guardian_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='email',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='guardian_created_at',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='guardian_updated_at',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='guardianusername',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='name',
        ),
        migrations.AddField(
            model_name='guardian',
            name='address_floor',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='cp',
            field=models.IntegerField(default=11012),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='via_name',
            field=models.CharField(default='CL', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guardian',
            name='via_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guardian',
            name='via_type',
            field=models.CharField(choices=[('CL', 'Calle'), ('AV', 'Avenida'), ('CJ', 'Callejón'), ('BL', 'Bulevar'), ('CA', 'Camino')], default='CL', max_length=2),
        ),
    ]
