# Generated by Django 3.2.3 on 2021-06-01 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alumn_people_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='activated',
        ),
    ]
