# Generated by Django 3.2.3 on 2021-06-02 14:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210602_1602'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guardian',
            name='password',
        ),
        migrations.AlterField(
            model_name='alumn',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cicle',
            name='classroom',
            field=models.CharField(choices=[('0-1 años', '0-1 años'), ('1-2 años', '1-2 años'), ('2-3 años', '2-3 años'), ('3-4 años', '3-4 años'), ('4-5 años', '4-5 años'), ('5-6 años', '5-6 años')], default='0-1 años', max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='via_type',
            field=models.CharField(choices=[('CL', 'Calle'), ('AV', 'Avenida'), ('CJ', 'Callejón'), ('BL', 'Bulevar'), ('CA', 'Camino')], default='0-1 años', max_length=8),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
