# Generated by Django 3.2.3 on 2021-06-02 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20210602_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='via_type',
            field=models.CharField(choices=[('Calle', 'Calle'), ('Avenida', 'Avenida'), ('Callejón', 'Callejón'), ('Bulevar', 'Bulevar'), ('Camino', 'Camino')], default='Calle', max_length=8),
        ),
    ]
