# Generated by Django 3.2.3 on 2021-06-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_guardian_via_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='activated',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='newsletter',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='privacity',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='no', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='terms',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='no', max_length=2, null=True),
        ),
    ]
