# Generated by Django 3.2.3 on 2021-06-06 15:18

from django.db import migrations, models
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210606_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumn',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[users.models.validate_age_children]),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='activated',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[users.models.validate_age]),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='newsletter',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='privacity',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='terms',
            field=models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birth_date',
            field=models.DateField(default=django.utils.timezone.now, validators=[users.models.validate_age]),
        ),
    ]
