# Generated by Django 3.2.3 on 2021-06-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20210606_1718'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumn',
            options={'verbose_name': 'alumn', 'verbose_name_plural': 'alumns'},
        ),
        migrations.AlterModelOptions(
            name='cicle',
            options={'verbose_name': 'cicle', 'verbose_name_plural': 'cicles'},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={'verbose_name': 'guardian', 'verbose_name_plural': 'guardians'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'teacher', 'verbose_name_plural': 'teachers'},
        ),
        migrations.AlterModelTable(
            name='alumn',
            table='alumns',
        ),
        migrations.AlterModelTable(
            name='cicle',
            table='cicles',
        ),
        migrations.AlterModelTable(
            name='guardian',
            table='guardians',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
