# Generated by Django 3.2.3 on 2021-06-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210608_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='cicle',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guardian',
            options={},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={},
        ),
    ]
