# Generated by Django 3.2.3 on 2021-06-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20210608_0229'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumn',
            table=None,
        ),
        migrations.AlterModelTable(
            name='cicle',
            table=None,
        ),
        migrations.AlterModelTable(
            name='guardian',
            table=None,
        ),
        migrations.AlterModelTable(
            name='teacher',
            table=None,
        ),
    ]
