# Generated by Django 3.2.3 on 2021-06-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20210608_0905'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='alumn',
            table='alumns',
        ),
        migrations.AlterModelTable(
            name='cicle',
            table='cicles',
        ),
        migrations.AlterModelTable(
            name='guardian',
            table='guardians',
        ),
        migrations.AlterModelTable(
            name='teacher',
            table='teachers',
        ),
    ]
