# Generated by Django 3.2.3 on 2021-05-19 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('event_date', models.DateField()),
                ('event_Description', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('new_id', models.AutoField(primary_key=True, serialize=False)),
                ('new_title', models.CharField(max_length=200)),
                ('new_content', models.CharField(max_length=1400)),
                ('new_media1', models.ImageField(upload_to='')),
            ],
        ),
    ]
