# Generated by Django 3.2.3 on 2021-05-19 15:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210519_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='event_updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='new',
            name='new_created_at',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='new',
            name='new_updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
