# Generated by Django 3.2.3 on 2021-05-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_new_new_media1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_subtitle',
            field=models.CharField(max_length=50),
        ),
    ]
