# Generated by Django 3.2.3 on 2021-05-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_new_new_subtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_media1',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
