# Generated by Django 3.2.3 on 2021-05-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_new_new_media1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='new_media1',
            field=models.ImageField(upload_to='static/core/recursos/images/news'),
        ),
    ]
