# Generated by Django 3.2.3 on 2021-05-20 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210520_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(choices=[('1E', '0-1 años'), ('2E', '1-2 años'), ('3E', '2-3 años'), ('4E', '3-4 años'), ('5E', '4-5 años'), ('6E', '5-6 años')], default='1E', max_length=2)),
                ('menu_image', models.ImageField(upload_to='images/menus')),
                ('menu_created_at', models.DateField(auto_now_add=True)),
                ('menu_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('age', models.CharField(choices=[('1E', '0-1 años'), ('2E', '1-2 años'), ('3E', '2-3 años'), ('4E', '3-4 años'), ('5E', '4-5 años'), ('6E', '5-6 años')], default='1E', max_length=2)),
                ('timetable_image', models.ImageField(upload_to='images/timetables')),
                ('timetable_created_at', models.DateField(auto_now_add=True)),
                ('timetable_updated_at', models.DateField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='people',
            name='image',
            field=models.ImageField(default='', upload_to='images/people'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='new',
            name='media1',
            field=models.ImageField(upload_to='images/news'),
        ),
    ]
