# Generated by Django 3.2.3 on 2021-05-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210520_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='menu_image',
            field=models.ImageField(upload_to='menus'),
        ),
        migrations.AlterField(
            model_name='new',
            name='media1',
            field=models.ImageField(upload_to='news'),
        ),
        migrations.AlterField(
            model_name='people',
            name='image',
            field=models.ImageField(upload_to='people'),
        ),
        migrations.AlterField(
            model_name='timetable',
            name='timetable_image',
            field=models.ImageField(upload_to='timetables'),
        ),
    ]
