# Generated by Django 3.2.3 on 2021-05-23 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alumn_guardian'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardian',
            name='activated',
            field=models.CharField(choices=[('no', 'no'), ('si', 'si')], default='no', max_length=2),
        ),
    ]
