# Generated by Django 3.2.3 on 2021-05-23 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_guardian_activated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guardian',
            name='phone',
            field=models.CharField(max_length=9),
        ),
    ]
