# Generated by Django 3.2.3 on 2021-05-24 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_guardian_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='New',
        ),
    ]
