# Generated by Django 3.2.3 on 2021-05-25 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('core', '0017_delete_new'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumn',
            name='legal_tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guardian'),
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
    ]
