# Generated by Django 3.2.3 on 2021-05-27 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210525_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumn',
            name='image',
            field=models.ImageField(blank=True, upload_to='alumns'),
        ),
    ]
