# Generated by Django 3.2.3 on 2021-05-31 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_alumn_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumn',
            name='legal_tutor',
        ),
        migrations.DeleteModel(
            name='People',
        ),
        migrations.DeleteModel(
            name='Alumn',
        ),
    ]
