# Generated by Django 3.2.3 on 2021-06-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210608_0209'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
