# Generated by Django 3.2.3 on 2021-06-08 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210608_0211'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date'], 'verbose_name': 'event', 'verbose_name_plural': 'events'},
        ),
    ]
