# Generated by Django 3.2.3 on 2021-06-08 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='resource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='timetable',
            options={},
        ),
    ]
