# Generated by Django 3.2.3 on 2021-06-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_alter_event_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelTable(
            name='event',
            table=None,
        ),
        migrations.AlterModelTable(
            name='menu',
            table=None,
        ),
        migrations.AlterModelTable(
            name='resource',
            table=None,
        ),
        migrations.AlterModelTable(
            name='timetable',
            table=None,
        ),
    ]
