# Generated by Django 3.2.3 on 2021-06-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20210608_0905'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
        migrations.AlterModelTable(
            name='menu',
            table='menus',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='resources',
        ),
        migrations.AlterModelTable(
            name='timetable',
            table='timetables',
        ),
    ]
