# Generated by Django 3.2.4 on 2021-06-10 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('birth_date', models.DateField(default=django.utils.timezone.now, validators=[users.models.validate_age])),
                ('via_type', models.CharField(choices=[('Calle', 'Calle'), ('Avenida', 'Avenida'), ('Callejón', 'Callejón'), ('Bulevar', 'Bulevar'), ('Camino', 'Camino')], default='Calle', max_length=8)),
                ('via_name', models.CharField(max_length=100)),
                ('via_number', models.IntegerField(default=0)),
                ('address_floor', models.IntegerField()),
                ('floor_letter', models.CharField(default='', max_length=9)),
                ('cp', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'teachers',
            },
        ),
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('guardiancode', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('birth_date', models.DateField(default=django.utils.timezone.now, validators=[users.models.validate_age])),
                ('via_type', models.CharField(choices=[('Calle', 'Calle'), ('Avenida', 'Avenida'), ('Callejón', 'Callejón'), ('Bulevar', 'Bulevar'), ('Camino', 'Camino')], default='Calle', max_length=8)),
                ('via_name', models.CharField(max_length=100)),
                ('via_number', models.IntegerField(default=0)),
                ('address_floor', models.IntegerField()),
                ('floor_letter', models.CharField(default='', max_length=9)),
                ('cp', models.IntegerField()),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='legal-guardian')),
                ('phone', models.CharField(max_length=9)),
                ('privacity', models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True)),
                ('activated', models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True)),
                ('terms', models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True)),
                ('newsletter', models.CharField(blank=True, choices=[('No', 'No'), ('Si', 'Si')], default='No', max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'guardians',
            },
        ),
        migrations.CreateModel(
            name='Cicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('classroom', models.CharField(choices=[('0-1 años', '0-1 años'), ('1-2 años', '1-2 años'), ('2-3 años', '2-3 años'), ('3-4 años', '3-4 años'), ('4-5 años', '4-5 años'), ('5-6 años', '5-6 años')], default='0-1 años', max_length=8, unique=True)),
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.teacher')),
            ],
            options={
                'db_table': 'cicles',
            },
        ),
        migrations.CreateModel(
            name='Alumn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=150)),
                ('birth_date', models.DateField(default=django.utils.timezone.now, validators=[users.models.validate_age_children])),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, upload_to='alumns')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cicle')),
                ('legal_tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.guardian')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alumns',
            },
        ),
    ]
