# Generated by Django 3.2.4 on 2021-06-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210611_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumn',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='alumn',
            name='name',
        ),
    ]
