# Generated by Django 3.2.3 on 2021-05-24 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1400)),
                ('media1', models.ImageField(upload_to='news')),
                ('media2', models.ImageField(blank=True, upload_to='')),
                ('media3', models.ImageField(blank=True, upload_to='')),
                ('media4', models.ImageField(blank=True, upload_to='')),
                ('media5', models.ImageField(blank=True, upload_to='')),
                ('media6', models.ImageField(blank=True, upload_to='')),
                ('new_created_at', models.DateField(auto_now_add=True)),
                ('new_updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
