# Generated by Django 3.2.3 on 2021-05-25 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_new_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='media2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='media3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='media4',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='media5',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='new',
            name='media6',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
