# Generated by Django 3.2.3 on 2021-06-01 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20210525_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(max_length=3000),
        ),
    ]
