# Generated by Django 3.2.3 on 2021-06-08 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_new_options'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='new',
            table=None,
        ),
    ]
