# Generated by Django 3.2.3 on 2021-06-08 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_alter_new_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='new',
            table='news',
        ),
    ]
