# Generated by Django 3.2.4 on 2021-06-10 10:05

from django.db import migrations, models
import django.db.models.deletion
import portal.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(validators=[portal.models.validate_date])),
                ('Description', models.CharField(max_length=400)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'events',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=3000)),
                ('media1', models.ImageField(upload_to='news')),
                ('media2', models.ImageField(blank=True, null=True, upload_to='')),
                ('media3', models.ImageField(blank=True, null=True, upload_to='')),
                ('media4', models.ImageField(blank=True, null=True, upload_to='')),
                ('media5', models.ImageField(blank=True, null=True, upload_to='')),
                ('media6', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=400)),
                ('resource_created_at', models.DateField(auto_now_add=True)),
                ('resource_updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('timetable_image', models.ImageField(upload_to='timetables')),
                ('timetable_created_at', models.DateField(auto_now_add=True)),
                ('timetable_updated_at', models.DateField(auto_now=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('cicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.cicle')),
            ],
            options={
                'db_table': 'timetables',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_image', models.ImageField(upload_to='menus')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('cicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.cicle')),
            ],
            options={
                'db_table': 'menus',
            },
        ),
    ]
