# Generated by Django 3.2.4 on 2021-06-11 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
